language: python

python:
   - 2.7
   - 3.6

install:
  - pip install lxml futures numpy
  - python setup.py install

script:
  - pytest

notifications:
  email: false
  slack: realfastvla:ID1qIFG70HGYf3G6Y3oWoFFk
