language: python

python:
   - 2.7
   - 3.6

install:
  - pip install coverage codecov
  - python setup.py install

#script:
#  - pytest

script: 
  - coverage run --source sdmpy -m py.test

after_success:
  - coverage report
  - codecov

notifications:
  email: false
  slack: realfastvla:ID1qIFG70HGYf3G6Y3oWoFFk
